---

- name: Output NodeJS major version to use
  ansible.builtin.debug:
    var: nodejs_version

- ansible.builtin.include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- ansible.builtin.include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Define nodejs_install_npm_user
  ansible.builtin.set_fact:
    nodejs_install_npm_user: "{{ ansible_user_id }}"
  when: nodejs_install_npm_user is not defined

- name: get user facts for nodejs_install_npm_user
  ansible.builtin.user:
    name: "{{ nodejs_install_npm_user }}"
  register: nodejs_install_npm_user_facts

- name: Create npm global directory
  ansible.builtin.file:
    path: "{{ npm_config_prefix }}"
    owner: "{{ nodejs_install_npm_user }}"
    ansible.builtin.group: "{{ nodejs_install_npm_user_facts.group }}"
    state: directory

- name: Add npm_config_prefix bin directory to global $PATH.
  ansible.builtin.template:
    src: npm.sh.j2
    dest: /etc/profile.d/npm.sh
    mode: 0644

- name: Ensure npm global packages are at the latest release.
  community.general.npm:
    name: "{{ item.name }}"
    version: "{{ item.version | default('latest') }}"
    global: yes
    state: latest
  environment:
    NPM_CONFIG_PREFIX: "{{ npm_config_prefix }}"
    NODE_PATH: "{{ npm_config_prefix }}/lib/node_modules"
    NPM_CONFIG_UNSAFE_PERM: "{{ npm_config_unsafe_perm }}"
  with_items: "{{ nodejs_npm_global_packages }}"
